### ISSUE TITLE
forkをやめる

### ISSUE THREAD

**Issue by kou** [ruby/rurema-search#2]
@hsbt 今はroブランチにclear-code/rurema-searchに少しパッチがあたったものとデプロイ用のファイルが入っていますが、これを、デプロイ用のファイルだけにして、アプリケーションはclear-code/rurema-searchのものを使うようにしてよいですか？

2つのブランチをメンテナンスする（clear-code/rurema-searchに変更をいれたらruby/rurema-searchにマージするとか）のは手間なので、メンテナンスを楽にするために一元化したいのです。

**Comment by hsbt** [comment]
問題ありませんが

 * https://github.com/ruby/rurema-search/commit/126e87b1b29ac5bf0e00033eea6aa00c64fe52ea のようなセキュリティの修正を upstream 入れることは可能ですか?
 * メンテナンスしている都合上、upstream へのコミット権を @hsbt にも欲しい
  * いきなり master を変更はしません
 * 一元化の作業は @kou がやる

というのが僕の第一感触です。いかがでしょう?

**Comment by kou** [comment]
> * 126e87b のようなセキュリティの修正を upstream 入れることは可能ですか?

可能です。（入れます。）

> メンテナンスしている都合上、upstream へのコミット権を @hsbt にも欲しい

とりあえずpull requestを送ってください。私の反応が遅いとか私がボトルネックになるようならそのときに検討するのでどうでしょうか。

> 一元化の作業は @kou がやる

そのつもりです。

なので、2番目のやつの合意がとれれば進めていいのかなぁと思いました。

**Comment by hsbt** [comment]
> 2番目のやつの合意がとれれば進めていいのかなぁ

docs.ruby-lang.org の管理責任は僕にあるので、@hsbt のコントロール化にないアプリケーションを動かすのは受け入れがたいです。セキュリティの問題も含めて @kou さんが面倒をみるということなら良いですが、即日対応など可能でしょうか?

**Comment by kou** [comment]
> セキュリティの問題も含めて @kou さんが面倒をみるということなら良いですが、即日対応など可能でしょうか?

いつも対応するのはムリです。（たとえば旅行していてインターネットにつながらないとか。）

そのときはアプリケーションを止めるというのはどうでしょうか？

**Comment by kou** [comment]
あ、普段は対応しますよ。

**Comment by kou** [comment]
私が懸念しているのは @hsbt がmasterに直接やらないで、ブランチにセキュリティー対策などを入れてそのままになって、気付いたらmasterとブランチの2本のメンテナンスラインになることです。（今の状態と変わっていないように感じる。）

必要な修正ならmasterに入れてメンテナンスラインを1つにしたいんですよ。

**Comment by hsbt** [comment]
ソフトウェアの対応待ちのために動いているアプリケーションを止めるというのは、ユーザーの利便性を非常に下げているので、それなら直接修正させてくれよ、というのが僕の意見です。これはセキュリティによらなくて、単純な不具合についても同様です。

**Comment by kou** [comment]
> ソフトウェアの対応待ちのために動いているアプリケーションを止めるというのは、ユーザーの利便性を非常に下げているので、それなら直接修正させてくれよ、というのが僕の意見です。

では、私が即日対応できなくて @hsbt さんが対応できるときは、pull requestにして`config/deploy.rb`の`set :repo_url`と`set :branch`を書き換えてデプロイし、私が対応できるようになったらpull requestをマージして`set :repo_url`と`set :branch`を戻すという運用にするのはどうでしょうか？

これなら「直接修正したものをすぐにデプロイする」と「メンテナンスラインを増やさない」を両立できるような気がしました。

> これはセキュリティによらなくて、単純な不具合についても同様です。

あ、不具合もですか。今、私はまさに不具合のやつ（ #3 ）を修正したかったんですよ。
たぶん、サブパスにデプロイした時用の処理がアプリケーション側に足りないのが問題なんですが、こういうのも @hsbt さんが対応するつもりだったんですね。私が対応する範囲かなぁと思っていたので認識が間違っていました。すみません。。。

**Comment by hsbt** [comment]
> では、私が即日対応できなくて @hsbt さんが対応できるときは、pull requestにしてconfig/deploy.rbのset :repo_urlとset :branchを書き換えてデプロイし、私が対応できるようになったらpull requestをマージしてset :repo_urlとset :branchを戻すという運用にするのはどうでしょうか？

fork の ro に upstream の master をマージするよりも面倒になってる気がします。

> こういうのも @hsbt さんが対応するつもりだったんですね。私が対応する範囲かなぁと思っていたので認識が間違っていました。すみません。。。

問題が起きているというのは先ほど把握しましたが、対応するかどうかまでは考えていません。書いてもいないことを皮肉っぽく想像で言われるのは気分が悪いです。

ところで、ro ブランチで入れた変更を @hsbt が upstream に pull request 出すようにすれば問題は解決しますか?

**Comment by kou** [comment]
> 問題が起きているというのは先ほど把握しましたが、対応するかどうかまでは考えていません。

うーん、では、私の認識（ #3 は私が対応する範囲）は間違っていなかったということですか。

> 書いてもいないことを皮肉っぽく想像で言われるのは気分が悪いです。

すみませんでした。

> ところで、ro ブランチで入れた変更を @hsbt が upstream に pull request 出すようにすれば問題は解決しますか?

解決するような気もするし、しないような気もします。
pull requestがマージされた状態のときは`git diff upstream/master..ro`の結果にはデプロイ関係のファイルのみが含まれているという運用、という認識であっていますか？その認識であっているなら解決します。
あっていないなら解決しない気がします。

あっているならその運用で私は納得したのでcloseしてもらえますか？

**Comment by hsbt** [comment]
> うーん、では、私の認識（ #3 は私が対応する範囲）は間違っていなかったということですか。

@kou さんが対応していただけるのであれば @hsbt のやることは減るので助かります。

> pull requestがマージされた状態のときはgit diff upstream/master..roの結果にはデプロイ関係のファイルのみが含まれているという運用、という認識であっていますか？

はい、そうなるようにしていきたいと思っています。

fork することでメンテナンスの手間暇を増やし、ご迷惑をおかけしていますが、コントロールできないソフトウェアを root の責任があるサーバーに入れるのは避けたい、という点はご理解ください。

**Comment by kou** [comment]
>> うーん、では、私の認識（ #3 は私が対応する範囲）は間違っていなかったということですか。
> 
> @kou さんが対応していただけるのであれば @hsbt のやることは減るので助かります。

わかりました。

では対応しておきます。

>> pull requestがマージされた状態のときはgit diff upstream/master..roの結果にはデプロイ関係のファイルのみが含まれているという運用、という認識であっていますか？
> 
> はい、そうなるようにしていきたいと思っています。

確認ありがとうございます。
それでは、 https://github.com/ruby/rurema-search/commit/126e87b1b29ac5bf0e00033eea6aa00c64fe52ea などroにだけ入っている変更を確認してupstreamにマージしてroを最新にするところもこちらでやっておきます。（#3の修正をroに入れるときに必要になるため。）

> fork することでメンテナンスの手間暇を増やし、ご迷惑をおかけしていますが、コントロールできないソフトウェアを root の責任があるサーバーに入れるのは避けたい、という点はご理解ください。

はい、わかりました。
