### ISSUE TITLE
「%i」を検索するとエラーが発生する

### ISSUE THREAD

**Issue by kou** [ruby/rurema-search#3]
clear-code/rurema-search#21 はrurema.clear-code.comだと発生せず、docs.ruby-lang.orgだけで発生するのでこっちで対応する。

**Comment by takiy33** [comment]
修正ありがとうございました。

**Comment by hsbt** [comment]
@kou https://docs.ruby-lang.org/ja/search/query:%25i/ を見る限りエラーは発生しないようですが、再現手順異なったりします?

**Comment by kou** [comment]
調べていなくてすみません。。。すっかり忘れていました。
再現しないということはどこかで直ったんだと思います。

**Comment by hsbt** [comment]
ではどこかの何かで直ったということで...
