### ISSUE TITLE
https://docs.ruby-lang.org/ja/search/ の「るりまプロジェクト」のリンクが壊れている

### ISSUE THREAD

**Issue by takkanm** [ruby/rurema-search#5]
トップページ末尾にある「るりまプロジェクト」へのリンクが存在しないページへのリンクになっているようです。
なお、clear-code/rurema-search では直っているようです。

**Comment by hsbt** [comment]
報告ありがとうございます。早速ですが upstream (clea-code/rurema-search ) の修正を取り込んでデプロイして直しました。
