### ISSUE TITLE
Support Google Analytics

### ISSUE THREAD

**Issue by okkez** [ruby/rurema-search#6]
https://github.com/clear-code/rurema-search/pull/26 を upstream の master にマージしました。
あとサーバー上の document.yaml に必要な設定を追加したので、↑をマージしたものをデプロイすればdocs.ruby-lang.org/ja/search/ のるりまサーチにGoogle Analytics のスニペットが入ります。

@hsbt お手数ですが、デプロイしてもらってもいいでしょうか？

**Comment by hsbt** [comment]
デプロイします!

**Comment by hsbt** [comment]
デプロイしました!

GA タグが入ってる気配を感じます。

**Comment by okkez** [comment]
確認しました！ありがとうございます！
